#!/usr/bin/env bash
set -ex

# shellcheck source=../helpers/device-control
source "$( dirname "$0" )/../helpers/device-control"

cd "$( dirname "$0" )/../.."

export GOROOT=/usr/local/go
export PATH=$GOROOT/bin:$PATH

export GOPATH=$PWD
export PATH=$GOPATH/bin:$PATH

cd src/code.cloudfoundry.org/garden-shed

permit_device_control
create_loop_devices 256

# make sure we don't run vet on the vendor directory because there's legacy over there
ls -d */ | grep -v vendor | xargs -n 1 go tool vet -printf=false
ginkgo --tags daemon -r -p --race --keepGoing --nodes=8 --failOnPending --randomizeSuites "$@"
