#!/usr/bin/env bash
# vim: set ft=sh
set -ex

# shellcheck source=../helpers/device-control
source "$( dirname "$0" )/../helpers/device-control"

permit_device_control
create_loop_devices 256

export GOPATH="${PWD}/gr-release-develop"

cd gr-release-develop/src/thresholder

ginkgo --race -r --randomizeAllSpecs "$@"
