#!/usr/bin/env bash
set -euo pipefail

xargs="xargs -r"
if [ "$(uname)" == "Darwin" ]; then
  xargs="xargs"
fi

log() {
  echo ""
  echo "----------------------------------------------------------------------"
  echo "$(date) | slowmobius: $1"
  echo "----------------------------------------------------------------------"
  echo ""
}

function post_to_slack () {
  log "hit me with that time beam!"
  SLACK_MESSAGE="A \`$BUILD_JOB_NAME\` build is taking a very long time to finish ..."

  curl -s -X POST --data \
    "payload={\"text\": \"${SLACK_MESSAGE}\",\"username\":\"Slow Mobius\",\"icon_url\":\"${SLOW_MOBIUS_ICON_URL}\"}" \
    "${SLOW_MOBIUS_SLACK_URL}" > /dev/null
}

sleep_then_alert() {
  sleep "$SLOW_MOBIUS_TIME_LIMIT_SECONDS"
  post_to_slack
}

kill_child_processes() {
  kill "$watcher_pid"
  kill "$child_pid"
}

log "Running with timeout ${SLOW_MOBIUS_TIME_LIMIT_SECONDS}s"

"$@" & child_pid=$!
sleep_then_alert & watcher_pid=$!
trap kill_child_processes INT TERM

set +e
wait "$child_pid"
child_exit=$?
set -e

log "Child process exited with $child_exit. Killing background watcher"
# Reap zombies before trying to kill all jobs
jobs > /dev/null 2>&1
jobs -p | $xargs -n 1 kill
exit "$child_exit"
