#!/bin/bash
# vim: set ft=sh

set -e -x

source $(dirname $0)/aufs
cd $(dirname $0)/../..

export GOROOT=/usr/local/go
export GOPATH=$PWD
export PATH=$PATH:$GOPATH/bin:/var/gdn/assets/linux/bin
pushd src/code.cloudfoundry.org/idmapper/cmd/maximus
go install
popd

BUCKETBENCH_THREADS=${BUCKETBENCH_THREADS:=5}
BUCKETBENCH_ITERATIONS=${BUCKETBENCH_ITERATIONS:=50}
GDN_PATH="../gdn-linux-release/gdn"

GARDEN_ADDRESS=$(hostname)
GARDEN_IP=0.0.0.0
GARDEN_PORT=7777
GARDEN_DEBUG_PORT=17013
NESTED=true

tmpdir=/tmp/dir
rm -fr $tmpdir
mkdir $tmpdir
mount -t tmpfs none $tmpdir
mkdir $tmpdir/depot
mkdir $tmpdir/snapshots
mkdir $tmpdir/graph
permit_device_control
create_loop_devices 256
chmod 755 "$GDN_PATH"

$GDN_PATH \
  server \
  --depot=$tmpdir/depot \
  --graph=$tmpdir/graph \
  --bind-ip=$GARDEN_IP \
  --bind-port=$GARDEN_PORT \
  --debug-bind-ip=$GARDEN_IP \
  --debug-bind-port=$GARDEN_DEBUG_PORT \
  --log-level=$LOG_LEVEL \
  --uid-map-start=1 \
  --uid-map-length=$(($(maximus)-1)) \
  --gid-map-start=1 \
  --gid-map-length=$(($(maximus)-1)) \
  --default-rootfs=/opt/warden/rootfs &

# wait for server to start up
# and then curl to confirm that it is
sleep 5
curl ${GARDEN_ADDRESS}:${GARDEN_PORT}/ping

go get github.com/contraband/gaol
mkdir -p $GOPATH/src/github.com/estesp/bucketbench
git clone https://github.com/karampok/bucketbench.git $GOPATH/src/github.com/estesp/bucketbench
go install github.com/estesp/bucketbench

cat << EOF >> /tmp/bucketbench.yml
---
name: RunProcessBenchmark
image: alpine:latest
rootfs: /tmp/bundle
detached: true
drivers:
- type: Garden
  binary: gaol
  threads: ${BUCKETBENCH_THREADS}
  iterations: ${BUCKETBENCH_ITERATIONS}
- type: Runc
  binary: runc
  threads: ${BUCKETBENCH_THREADS}
  iterations: ${BUCKETBENCH_ITERATIONS}
commands:
- run
EOF

(
	mkdir -p /tmp/bundle
	cd /tmp/bundle
	runc spec
	sed -i 's/"terminal": true/"terminal": false/' config.json
	sed -i 's/"sh"/"whoami"/' config.json
	sed -i 's/"path": "rootfs"/"path": "\/opt\/warden\/rootfs"/' config.json
	sed -i 's/"process": {/"process": {\n"consoleSize": {"height":24,"width":80},\n/' config.json
)

bucketbench --log-level debug run --skip-limit -b /tmp/bucketbench.yml
