#!/usr/bin/env bash
set -e

export PATH
PATH="$(pwd)/bin:${PATH}"

export GOPATH
GOPATH="$(pwd)"

pushd cfbench-master
go build -mod vendor -o cfbench
popd

cf api "$CF_API" --skip-ssl-validation
cf auth

cf create-org "$CF_ORG"
cf target -o "$CF_ORG"
cf create-space "$CF_SPACE"
cf target -s "$CF_SPACE" -o "$CF_ORG"

# Clean up any cruft
cf apps | grep benchme | cut -d " " -f1 | xargs -n1 cf delete -r -f || true

export CF_AUTH_TOKEN
CF_AUTH_TOKEN="$(cf oauth-token)"

DOPPLER_ADDRESS=$(cf curl /v2/info | jq '.doppler_logging_endpoint' -r)
CF_ENV=${CF_ENV:-local}

dd if=/dev/urandom of=cf-acceptance-tests/assets/dora/big-file bs=10M count=9

./cfbench-master/cfbench \
  -stack "cflinuxfs3" \
  -action "$CF_ACTION" \
  -instances "$INSTANCES" \
  -host-name "$CF_ENV" \
  -app-dir cf-acceptance-tests/assets/dora \
  -output-format wavefront \
  -doppler-address "$DOPPLER_ADDRESS" >wavefront-metrics.txt

curl -H "Authorization: Bearer $WAVEFRONT_TOKEN" -F file=@- https://longboard.wavefront.com/report <wavefront-metrics.txt
