#!/usr/bin/env bash
set -e

export PATH
PATH="$( pwd )/bin:${PATH}"

export GOPATH
GOPATH="$( pwd )"

cf api https://api."$CF_DOMAIN" --skip-ssl-validation
cf login -u "$CF_USERNAME" -p "$CF_PASSWORD" -o system --skip-ssl-validation

cf create-org "$CF_ORG"
cf target -o "$CF_ORG"
cf create-space "$CF_SPACE"
cf target -s "$CF_SPACE" -o "$CF_ORG"

# Clean up any cruft
cf apps | grep dora | cut -d " " -f1 | xargs -n1 cf delete -r -f || true

export CF_AUTH_TOKEN
CF_AUTH_TOKEN="$( cf oauth-token )"

pushd cf-acceptance-tests/assets/dora
  cf push dora
popd

app_response=$(curl http://dora."$CF_DOMAIN")
if [[ "$app_response" != "Hi, I'm Dora!" ]]; then
  echo "ERROR: Unexpected response from app: $app_response"
  exit 1
fi
