#!/bin/bash
# vim: set ft=sh

set -e -x

VERSION=$(cat ./gr-version/number)
if [ -z "$VERSION" ]; then
  echo "missing version number"
  exit 1
fi

cd gr-release-develop/

bosh -n create release --with-tarball --version "${VERSION}"

mkdir -p ../bosh-release
mv dev_releases/garden-runc/*.tgz ../bosh-release/garden-runc-${VERSION}.tgz
