#!/bin/bash
# vim: set ft=sh

set -e -x

VERSION=$(cat ./guardian-version/number)
if [ -z "$VERSION" ]; then
  echo "missing version number"
  exit 1
fi

cd guardian-release/

bosh -n create release --with-tarball --version "${VERSION}"

mv dev_releases/guardian/*.tgz ../guardian-${VERSION}.tgz
