#!/usr/bin/env bash
set -eo pipefail

args=$@
[ "$args" == "" ] && args="-r integration"

grr_base=$PWD/gr-release-develop
cd "$grr_base"/src/dontpanic
go install github.com/onsi/ginkgo/ginkgo@latest
ginkgo -mod vendor -p -nodes 5 -race $args
