#!/bin/bash
set -e

args=$@
[ "$args" == "" ] && args="-r"

grr_base=$PWD/gr-release-develop
cd "$grr_base"/src/dontpanic
go install github.com/onsi/ginkgo/ginkgo@latest
ginkgo -mod vendor -p -nodes 5 -race -skipPackage integration $args
