#!/bin/bash
# vim: set ft=sh

set -ex

cd $(dirname $0)/../..

export GOROOT=/usr/local/go
export PATH=$GOROOT/bin:$PATH

export GOPATH=$PWD
export PATH=$GOPATH/bin:$PATH

cd src/github.com/cloudfoundry-incubator/garden

go install github.com/onsi/ginkgo/ginkgo

ginkgo -r -p -race -keepGoing -nodes=4 "$@"
