#!/usr/bin/env bash
set -ex

cd "$( dirname "$0" )/../.."

cd src/garden

go vet ./...
ginkgo -r -p --race --keepGoing --nodes="${GINKGO_NODES:-8}" --failOnPending --randomizeSuites --randomizeAllSpecs "$@"
