#!/bin/bash
# vim: set ft=sh

set -ex

cd $(dirname $0)/../..

export GOROOT=/usr/local/go
export PATH=$GOROOT/bin:$PATH

export GOPATH=$PWD
export PATH=$GOPATH/bin:$PATH

cd src/code.cloudfoundry.org/garden

go vet ./...
ginkgo -r -p -race -keepGoing -nodes=4 -failOnPending -randomizeSuites "$@"
