#!/bin/bash
# vim: set ft=sh

set -e -x

basedir=$PWD
grreleasedevelopdir="$basedir"/gr-release-develop

source $(dirname $0)/device-control
source $(dirname $0)/gats-utils
cd $(dirname $0)/../..

export GOROOT=/usr/local/go
export PATH=$GOROOT/bin:$PATH
export GOPATH=$PWD
export PATH=$GOPATH/bin:$PATH
export tmpdir=/tmp/dir

export GARDEN_ADDRESS=$(hostname)
export GARDEN_PORT=7777
export GARDEN_DEBUG_PORT=17013
export NESTED=true

mkdir -p $GOPATH/bin

GDN_PATH="../gdn-linux-release/gdn"
chmod 755 "$GDN_PATH"

build_runc "$grreleasedevelopdir"
build_nstar "$grreleasedevelopdir"
build_grootfs "$grreleasedevelopdir"
build_gdn "$grreleasedevelopdir"
build_idmapper_binaries "$grreleasedevelopdir"
setup_dirs
write_groot_config_file
setup_groot_stores
start_gdn_server "$GDN_PATH"

curl "${GARDEN_ADDRESS}:${GARDEN_PORT}/ping"

cd src/code.cloudfoundry.org/garden-integration-tests

cmd="ginkgo -p -nodes=8 -failOnPending -randomizeSuites -randomizeAllSpecs $*"
if [ -n "${SLOW_MOBIUS_TIME_LIMIT_SECONDS:-}" ]; then
  cmd="$base/gr-release-develop/ci/scripts/slowmobius $cmd"
fi

$cmd
