#!/usr/bin/env bash
set -ex

basedir=$PWD
grreleasedevelopdir="$basedir"/gr-release-develop

# shellcheck source=../helpers/device-control
source "$( dirname "$0" )/../helpers/device-control"

# shellcheck source=../helpers/gats-utils
source "$( dirname "$0" )/../helpers/gats-utils"

# shellcheck source=../../src/build/runc.bash
source "$( dirname "$0" )/../../src/build/runc.bash"

function build() {
  mkdir -p "${GOPATH}/bin"
  if [ -n "${PATCH_RUNC:-}" ]; then
    (
    # Using patch instead of `git apply` to keep this path working with `fly
    # execute`, which does not preserve the `.git` dir.
    cd "${grreleasedevelopdir}/src/gopath/src/github.com/opencontainers/runc"
    patch < "${grreleasedevelopdir}/ci/runc-patches/0001-remove-delete-timeout.patch"
    )
  fi
  build_runc "$grreleasedevelopdir" "${GOPATH}/bin"
  build_nstar "$grreleasedevelopdir"
  build_grootfs "$grreleasedevelopdir"
  build_mkdirer "$grreleasedevelopdir"
  build_gdn "$grreleasedevelopdir"
  if [[ "$CONTAINERD_ENABLED" == "true" ]] ; then
    build_containerd "$grreleasedevelopdir"
  fi
  build_idmapper_binaries "$grreleasedevelopdir"
}

function prepare() {
  setup_dirs
  write_groot_config_file
  setup_groot_stores
  if [[ "$CONTAINERD_ENABLED" == "true" ]] ; then
    write_containerd_config_file
    start_containerd
  fi
  start_gdn_server

  wait_for_gdn_server
}

function test() {
  cd src/garden-integration-tests

  cmd="ginkgo -mod vendor -p --nodes=${GINKGO_NODES:-8} --failOnPending --randomizeSuites --randomizeAllSpecs $*"
  if [ -n "${SLOW_MOBIUS_TIME_LIMIT_SECONDS:-}" ]; then
    cmd="$basedir/gr-release-develop/ci/helpers/slowmobius $cmd"
  fi

  $cmd
}

cd "$( dirname "$0" )/../.."

export GOPATH=$PWD/src/gopath
export PATH=$GOPATH/bin:$PATH
export tmpdir=/tmp/dir

export GARDEN_ADDRESS
GARDEN_ADDRESS="$( hostname )"
export GARDEN_PORT=7777
export GARDEN_DEBUG_PORT=17013
export NESTED=true

build
prepare
test "$*"
