#!/bin/bash
# vim: set ft=sh

set -e -x

source $(dirname $0)/aufs
cd $(dirname $0)/../..

export GOROOT=/usr/local/go
export PATH=$GOROOT/bin:$PATH
export GOPATH=$PWD
export PATH=$GOPATH/bin:$PATH

mkdir -p $GOPATH/bin

pushd src/github.com/opencontainers/runc
GOPATH=$PWD/Godeps/_workspace:$GOPATH go build -o runc .
mv runc $GOPATH/bin
popd

pushd src/github.com/cloudfoundry-incubator/guardian/rundmc/nstar
make
popd

pushd src/github.com/cloudfoundry-incubator/guardian
go install -tags daemon github.com/cloudfoundry-incubator/guardian/cmd/guardian
go install github.com/cloudfoundry-incubator/guardian/rundmc/iodaemon/cmd/iodaemon
go install github.com/cloudfoundry-incubator/guardian/cmd/kawasaki
go install github.com/cloudfoundry-incubator/guardian/cmd/init

tmpdir=/tmp/dir
rm -fr $tmpdir
mkdir $tmpdir
mount -t tmpfs none $tmpdir

mkdir $tmpdir/depot
mkdir $tmpdir/snapshots
mkdir $tmpdir/graph

permit_device_control
create_loop_devices 256

$GOPATH/bin/guardian \
  -iodaemonBin=$GOPATH/bin/iodaemon \
  -kawasakiBin=$GOPATH/bin/kawasaki \
  -initBin=$GOPATH/bin/init \
  -nstarBin=./rundmc/nstar/nstar \
  -tarBin=/opt/tar \
  -depot=$tmpdir/depot \
  -graph=$tmpdir/graph \
  -bin=$PWD/linux_backend/bin \
  -listenNetwork=tcp \
  -listenAddr=0.0.0.0:7777 \
  -denyNetworks= \
  -allowNetworks= \
  -allowHostAccess=false \
  -mtu=1500 \
  -containerGraceTime=5m \
  -logLevel=debug \
  -rootfs=/opt/warden/rootfs &

sleep 5
popd

go install github.com/onsi/ginkgo/ginkgo
cd src/github.com/cloudfoundry-incubator/garden-integration-tests
export GARDEN_ADDRESS=$(hostname):7777
ginkgo -p -nodes=4 "$@"
