#!/usr/bin/env bash
set -ex

export PATH=$GOPATH/bin:$PATH

DEVELOP=$PWD/gr-release-develop

git clone ./gr-release-release ./release-merged

cd release-merged

git remote add local "$DEVELOP"

git fetch local
git checkout local/develop

git config --global user.email "ci@localhost"
git config --global user.name "CI Bot"

git merge --no-edit release
