#!/bin/bash
# vim: set ft=sh

set -ex

mkdir -p /var/run/oci
mount -t tmpfs tmpfs /var/run/oci

cd $(dirname $0)/../..

export GOROOT=/usr/local/go
export PATH=$GOROOT/bin:$PATH

export GOPATH=$PWD
export PATH=$GOPATH/bin:$PATH

pushd src/github.com/opencontainers/runc
GOPATH=$PWD/Godeps/_workspace:$GOPATH go build -o runc .
cp runc /usr/local/bin/runc
popd

cd src/github.com/cloudfoundry-incubator/guardian
go install github.com/onsi/ginkgo/ginkgo

export GARDEN_TEST_ROOTFS=/opt/warden/rootfs
ginkgo -tags daemon -r -p -race -cover -keepGoing -nodes=4 "$@"
