#!/bin/bash
# vim: set ft=sh

set -e -x

cd $(dirname $0)/../..

export GOROOT=/usr/local/go
export PATH=$GOROOT/bin:$PATH
export GOPATH=$PWD
export PATH=$GOPATH/bin:$PATH

pushd src/github.com/cloudfoundry-incubator/guardian

go install -tags daemon github.com/cloudfoundry-incubator/guardian/cmd/guardian/
go install github.com/cloudfoundry-incubator/guardian/rundmc/iodaemon/cmd/iodaemon

tmpdir=/tmp/dir
rm -fr $tmpdir
mkdir -p $tmpdir/depot
mkdir $tmpdir/snapshots
mkdir $tmpdir/graph

$GOPATH/bin/guardian \
  -iodaemonBin=$GOPATH/bin/iodaemon \
  -depot=$tmpdir/depot \
  -snapshots=$tmpdir/snapshots \
  -graph=$tmpdir/graph \
  -bin=$PWD/linux_backend/bin \
  -listenNetwork=tcp \
  -listenAddr=0.0.0.0:7777 \
  -denyNetworks= \
  -allowNetworks= \
  -allowHostAccess=false \
  -mtu=1500 \
  -containerGraceTime=5m \
  -logLevel=error \
  -rootfs=/opt/warden/rootfs &

popd

go install github.com/onsi/ginkgo/ginkgo
cd src/github.com/cloudfoundry-incubator/garden-integration-tests
export GARDEN_ADDRESS=$(hostname):7777
ginkgo -p -nodes=4 "$@"
