#!/usr/bin/env bash
set -ex

base=$PWD

cd "$( dirname "$0" )/../.."

cd src/garden-integration-tests

cmd="ginkgo --nodes=${GINKGO_NODES:-8} --failOnPending --randomizeSuites --randomizeAllSpecs -stream"
if [ -n "${SLOW_MOBIUS_TIME_LIMIT_SECONDS:-}" ]; then
  cmd="$base/gr-release-develop/ci/helpers/slowmobius $cmd"
fi

if [ -n "${WINDOWS_TEST_ROOTFS:-}" ]; then
  cmd="ginkgo -stream gats98"
fi

$cmd
