#!/usr/bin/env bash
set -ex

cd "$( dirname "$0" )/../.."

export GOPATH=$PWD
export PATH=$PWD/bin:$PATH

cd src/code.cloudfoundry.org/garden-integration-tests
ginkgo -p --nodes=4 --failOnPending performance
