#!/bin/bash
# vim: set ft=sh

set -ex

source $(dirname $0)/aufs
cd $(dirname $0)/../..

export GOROOT=/usr/local/go
export PATH=$GOROOT/bin:$PATH

export GOPATH=$PWD
export PATH=$GOPATH/bin:$PATH

cd src/github.com/cloudfoundry-incubator/garden-shed

go install github.com/onsi/ginkgo/ginkgo

permit_device_control
create_loop_devices 256

ginkgo -tags daemon -r -p -race -cover -keepGoing -nodes=4 "$@"
