#!/bin/bash
# vim: set ft=sh

set -e -x

VERSION=$(cat ./gr-version/number)
if [ -z "$VERSION" ]; then
  echo "missing version number"
  exit 1
fi

cp garden-ci/config/private.yml gr-release-develop/config/private.yml

CANDIDATE_DIR=$PWD/gr-candidate-tarball

cd gr-release-develop/

git config --global user.email "ci@localhost"
git config --global user.name "CI Bot"

RELEASE_YML=$PWD/releases/garden-runc/garden-runc-${VERSION}.yml

if [ -e ${RELEASE_YML} ]; then
  echo "release already created; making tarball..."
  bosh -n create release --with-tarball ${RELEASE_YML}
else
  echo "finalizing release"
  bosh -n finalize release --version "$VERSION" ${CANDIDATE_DIR}/garden-runc-*.tgz
  git add -A
  git commit -m "release v${VERSION}"
fi

mv releases/garden-runc/*.tgz ../final-release/garden-runc-${VERSION}.tgz
cp -r . ../release/master
