#!/bin/bash
# vim: set ft=sh

set -e -x

VERSION=$(cat ./garden-runc-version/number)
if [ -z "$VERSION" ]; then
  echo "missing version number"
  exit 1
fi

cp garden-ci/config/private.yml gr-release-develop/config/private.yml

CANDIDATE_DIR=$PWD/guardian-candidate-tarball

cd gr-release-develop/

git config --global user.email "ci@localhost"
git config --global user.name "CI Bot"

git merge --no-edit master

bosh -n finalize release --version "$VERSION" ${CANDIDATE_DIR}/guardian-*.tgz

mv releases/guardian/*.tgz ../final-release/guardian-${VERSION}.tgz

git add -A
git commit -m "release v${VERSION}"

cp -r . ../release/master
