#!/bin/bash
# vim: set ft=sh

set -e -x

source $(dirname $0)/device-control
permit_device_control
create_loop_devices 256

export GOPATH=$PWD/gr-release-develop

cd gr-release-develop/src/thresholder

ginkgo -race -r --randomizeAllSpecs "$@"
