#!/usr/bin/env bash
set -ex

# shellcheck source=../helpers/device-control
source "$( dirname "$0" )/../helpers/device-control"

permit_device_control
create_loop_devices 256

cd gr-release-develop/src/thresholder

go install github.com/onsi/ginkgo/ginkgo@latest
ginkgo -mod vendor --race -r --randomizeAllSpecs "$@"
