---
name: ((deployment))

releases:
- name: garden-runc
  version: latest
- name: winc
  version: latest
- name: windows-utilities
  version: latest
- name: garden-ci-artifacts
  version: latest

stemcells:
- alias: windows2019
  os: windows2019
  version: latest
- alias: stemcell
  os: ((stemcell-os))
  version: latest

instance_groups:
- name: gats
  instances: 1
  lifecycle: errand
  vm_type: ((vm))
  networks:
  - name: ((network))
  azs: [((az))]
  stemcell: stemcell
  jobs:
  - name: gats
    release: garden-runc
    properties:
      windows_rootfs: docker://mcr.microsoft.com/windows/nanoserver:ltsc2019
- name: garden-windows
  instances: 1
  vm_type: small-highmem
  vm_extensions:
    - 100GB_ephemeral_disk
  stemcell: windows2019
  azs: [((az))]
  networks:
  - name: ((network))
  jobs:
  - name: enable_ssh
    release: windows-utilities
  - name: garden-plugins
    release: garden-ci-artifacts
  - name: garden-windows
    release: garden-runc
    properties:
      garden:
        runtime_plugin: C:\var\vcap\packages\winc\winc.exe
        image_plugin: C:\var\vcap\packages\groot\groot.exe
        image_plugin_extra_args:
        - "--driver-store"
        - C:\var\vcap\data\groot
        network_plugin: C:\var\vcap\packages\noop_plugin\noop_plugin.exe
        nstar_bin: C:\var\vcap\packages\noop_plugin\noop_plugin.exe
        listen_address: 0.0.0.0:7777
        default_container_rootfs: docker://mcr.microsoft.com/windows/nanoserver:ltsc2019
        destroy_containers_on_start: true
  - name: winc
    release: winc
  - name: groot
    release: winc
    properties:
      groot:
        driver_store: C:\var\vcap\data\groot

update:
  canaries: 1
  max_in_flight: 3
  canary_watch_time: 1000-240000
  update_watch_time: 1000-240000
