#!/usr/bin/env bash
set -ex

base=$PWD

cd "$( dirname "$0" )/../.."

export GOPATH=$PWD
export PATH=$PWD/bin:$PATH

cd src/code.cloudfoundry.org/garden-integration-tests

cmd="ginkgo -p --nodes=${GINKGO_NODES:-8} --failOnPending --randomizeSuites --randomizeAllSpecs"
if [ -n "${SLOW_MOBIUS_TIME_LIMIT_SECONDS:-}" ]; then
  cmd="$base/gr-release-develop/ci/helpers/slowmobius $cmd"
fi

$cmd
