#!/usr/bin/env bash
set -euo pipefail

base=$PWD

# shellcheck source=../helpers/gdn-version
source "$( dirname "$0" )/../helpers/gdn-version"

VERSION=$(cat "$base"/gr-version/number)
if [ -z "${VERSION:-}" ]; then
  echo "missing version number"
  exit 1
fi

(
cd gr-release-develop

tarball_path="$base/bosh-release/garden-runc-${VERSION}.tgz"
mkdir -p "$(dirname "$tarball_path")"

# If you want to fly execute this, you will have to pass DEV_MODE=true
if [ -z "$DEV_MODE" ]; then
  ensure_release_is_clean "$PWD"
  create_gdn_version_file "$PWD"
fi

bosh -n create-release --sha2 --force --tarball="$tarball_path" --version="${VERSION}"
)
