#!/usr/bin/env bash
set -euo pipefail

base=$PWD

VERSION=$(cat "$base"/gr-version/number)
if [ -z "${VERSION:-}" ]; then
  echo "missing version number"
  exit 1
fi

(
cd gr-release-develop

tarball_path="$base/bosh-release/garden-runc-${VERSION}.tgz"
mkdir -p "$(dirname "$tarball_path")"
bosh -n create-release --sha2 --tarball="$tarball_path" --version="${VERSION}"
)
