#!/usr/bin/env bash
set -ex

ROOT_DIR_PATH=$(cd "$(dirname "$0")"/.. && pwd)
cd "$ROOT_DIR_PATH"

./scripts/check

./scripts/sync-submodule-config

./scripts/commit-with-submodule-log "$@"

git duet-commit --amend --reset-author --verbose
