#!/usr/bin/env bash
set -ex

ROOT_DIR_PATH=$(cd "$(dirname "$0")"/.. && pwd)
cd "$ROOT_DIR_PATH"

./scripts/check

git submodule foreach --quiet 'echo $path' | xargs git add

./scripts/commit-with-submodule-log "$@"

git commit --amend --reset-author --verbose
