#!/usr/bin/env ruby

require 'open3'
require 'logger'

PROJECTS = [
  "garden",
  "garden-integration-tests",
  "guardian",
  "grootfs",
  "idmapper",
  "netplugin-shim",
]

LOGGER = Logger.new(STDERR)
LOGGER.level = ARGV[0] == "-v" ? Logger::DEBUG : Logger::WARN

def with_go_mod_vendor(&block)
  begin
    PROJECTS.each do |project|
      exec_on_project(project, "go mod vendor")
    end
    block.call
  rescue => e
    LOGGER.error "mod vendor failed: #{e}"
  ensure
    PROJECTS.each do |project|
      exec_on_project(project, "git checkout vendor")
    end
  end
end

def with_stashed_projects(&block)
  actually_shashed_projects = []
  begin
    PROJECTS.each do |project|
      unless exec_on_project(project, "git status --porcelain").empty?
        actually_shashed_projects << project
        exec_on_project(project, "git stash --include-untracked")
      end
    end
    block.call
  rescue => e
    LOGGER.error "git stash failed: #{e}"
  ensure
    actually_shashed_projects.each do |project|
      exec_on_project(project, "git stash pop")
    end
  end
end

def check_vendor_is_unchanged
  projects_with_changed_vendor = []
  PROJECTS.each do |project|
    projects_with_changed_vendor << project unless has_changes_in_vendor?(project)
  end
  projects_with_changed_vendor
end

def has_changes_in_vendor?(project)
  exec("cd src/#{project}; git status --porcelain vendor").empty?
end

def exec_on_project(project, cmd)
  exec("cd src/#{project}; #{cmd}")
end

def exec(cmd)
  stdout, stderr, status = Open3.capture3(cmd)
  LOGGER.debug "command: '#{cmd}', exitcode: #{status}, stdout: '#{stdout}', stderr: '#{stderr}'"
  raise "command failed: #{stderr}" unless status.success?
  return stdout
end

with_stashed_projects do
 with_go_mod_vendor do
    projects_with_changed_vendor = check_vendor_is_unchanged
    unless projects_with_changed_vendor.empty?
      puts "The following projects have an out of date vendor folder. Considering running 'go mod vendor' and re-running your tests"
      projects_with_changed_vendor.each { |p| puts "* #{p}" }
      exit(1)
    end
  end
end
