#!/usr/bin/env bash

if [[ "$BASH_VERSINFO" -lt "4" ]]; then
  echo "Requires bash-4.2+. Make sure you've updated from garden-dotfiles."
  exit 1
fi

declare -A deps
deps[guardian]="idmapper grootfs garden"
deps[grootfs]="idmapper"

ok=0

for proj in "${!deps[@]}"; do

  for dep in ${deps[$proj]}; do
    pushd "src/$dep" &> /dev/null

    git fetch
    long_sha=$(git rev-parse origin/master)
    short_sha="${long_sha:0:12}"

    popd &> /dev/null

    if ! grep -q "$short_sha" "src/$proj/go.mod"; then
      echo "$dep not up to date in $proj - latest version is $long_sha"
      ok=1
    fi
  done

done

if [[ "$ok" -eq "0" ]]; then

  for proj in "${!deps[@]}"; do
    pushd "src/$proj" &> /dev/null
      if [ -n "$(git status --porcelain vendor)" ]; then
        echo "$proj/vendor has local modifications"
        ok=1
      else
        go mod vendor
        if [ -n "$(git status --porcelain vendor)" ]; then
          echo "$proj/vendor is out of sync with go.mod"
          echo "run 'git checkout -- vendor' in src/$proj to undo changes from this script!"
          ok=1
        fi
      fi
    popd &> /dev/null
  done

fi

exit $ok
