#!/usr/bin/env bash
set -e

if [ "$(git rev-parse --abbrev-ref HEAD)" == "master" ]; then
  echo "Cannot bump in the master branch!"
  exit 1
fi

read -p "Did you make sure CI is green? (yes/no):" response
if  [ "$response" == "yes" ]; then
  echo "Thanks! Continuing with bump..."
else
  open "https://garden.ci.cf-app.com/"
  exit 1
fi
