#!/usr/bin/env bash
set -e

if [ "$(git rev-parse --abbrev-ref HEAD)" == "master" ]; then
  echo "Cannot bump in the master branch!"
  exit 1
fi

questions=("Did you check the weather?" "Is Ed a fallen star?" "Do you like the colour blue?" "Is Julz why we have bugs?")
question=${questions[$RANDOM % ${#questions[@]} ]}

read -p "$question (yes/no):"
echo "Thanks! Continuing with bump..."
