#!/bin/bash
ROOT_DIR_PATH=$(cd $(dirname $0)/.. && pwd)

gosub list \
  -a github.com/cloudfoundry-incubator/guardian/... \
  -t github.com/cloudfoundry-incubator/guardian/gqt/... \
  -t github.com/cloudfoundry-incubator/garden-integration-tests/... \
  -a github.com/opencontainers/specs/... \
  -a github.com/vishvananda/netns/... \
