#!/bin/bash
ROOT_DIR_PATH=$(cd $(dirname $0)/.. && pwd)

gosub list \
  -a code.cloudfoundry.org/guardian/... \
  -t code.cloudfoundry.org/guardian/gqt/... \
  -t code.cloudfoundry.org/garden-integration-tests/... \
  -a github.com/opencontainers/runtime-spec/... \
  -a github.com/vishvananda/netns/... \
  -t code.cloudfoundry.org/garden-shed/... \
  -a github.com/opencontainers/runc/libcontainer/label/... \
  -a github.com/docker/docker/pkg/directory/... \
  -a github.com/docker/docker/pkg/mount/... \
  -a github.com/vishvananda/netlink/... \
  -a github.com/opencontainers/runc/libcontainer/system/... \
  -a github.com/opencontainers/runc/libcontainer/cgroups/... \
  -a github.com/docker/go-units/... \
  -a github.com/golang/protobuf/... \
