#!/bin/bash -e

build_yml=$1
shift

if [ -z $GARDEN_REMOTE_ATC_URL ]; then
  fly -t lite login -c http://192.168.100.4:8080
  fly -t lite e -x -p -i garden-runc-release=. -c $build_yml $@
else
  fly --target $GARDEN_REMOTE_ATC_URL e -x -p -c $build_yml $@
fi
