#!/usr/bin/env bash
set -e

if [ ! -z "$TAG" ]; then
  tag="--tag $TAG"
fi

build_yml=$1
shift

fly --target "$GARDEN_REMOTE_ATC_URL" e $tag -p -i gr-release-develop=$HOME/workspace/garden-runc-release -c "$build_yml" "$@"
