#!/bin/bash

for mod in garden guardian grootfs idmapper netplugin-shim garden-integration-tests garden-performance-acceptance-tests; do
  pushd "src/$mod"
    git checkout master
    go mod tidy
    go mod vendor
    git add .
    git commit -m "go mod vendor"
  popd
done
