#!/bin/bash
set -e -x

ROOT_DIR_PATH=$(cd $(dirname $0)/.. && pwd)

# fail fast if gosub is not installed
which gosub
(
  sort -u \
    <(GOOS=darwin $ROOT_DIR_PATH/scripts/guardian-deps) \
    <(GOOS=linux $ROOT_DIR_PATH/scripts/guardian-deps) \
    <(GOOS=windows $ROOT_DIR_PATH/scripts/guardian-deps)
  echo "github.com/opencontainers/runc"
  echo "code.cloudfoundry.org/idmapper/cmd/maximus"
) | xargs gosub sync
