#!/usr/bin/env bash
set -ex

# fail fast if gosub is not installed
which gosub

function linux_deps {
  GOOS=linux gosub list \
    -t code.cloudfoundry.org/guardian/... \
    -t code.cloudfoundry.org/garden/... \
    -t code.cloudfoundry.org/garden-shed/... \
    -t code.cloudfoundry.org/garden-integration-tests/...
}

function windows_deps {
  GOOS=windows gosub list \
    -t code.cloudfoundry.org/guardian/... \
    -t code.cloudfoundry.org/garden/... \
    -t code.cloudfoundry.org/garden-integration-tests/...
}

function grootfs_deps {
  echo "code.cloudfoundry.org/grootfs"
}

(
  sort -u \
    <(linux_deps) \
    <(windows_deps) \
    <(grootfs_deps)

) | xargs gosub sync
