#!/bin/bash
set -e -x

ROOT_DIR_PATH=$(cd $(dirname $0)/.. && pwd)

pushd $ROOT_DIR_PATH/packages/guardian
  {
    cat spec | grep -v '# gosub'
    $ROOT_DIR_PATH/scripts/guardian-deps | \
      sed -e 's/\(.*\)/  - \1\/*.go # gosub/g'
  } > spec.new

  mv spec.new spec
popd

pushd $ROOT_DIR_PATH/packages/garden-idmapper
  {
    cat spec | grep -v '# gosub'
    gosub list \
      -a code.cloudfoundry.org/idmapper/cmd/newuidmap \
      -a code.cloudfoundry.org/idmapper/cmd/newgidmap \
      -a code.cloudfoundry.org/idmapper/cmd/maximus \
      | sed -e 's/\(.*\)/  - \1\/*.go # gosub/g'
  } > spec.new

  mv spec.new spec
popd
