#!/bin/bash -exu

if ! which bundler; then
  export PATH="/rbenv/bin:$HOME/.rbenv/plugins/ruby-build/bin:${PATH}"
  eval "$(rbenv init -)"
fi

ROOT_DIR_PATH="$(cd $(dirname $0)/.. && pwd)"

pushd "${ROOT_DIR_PATH}" > /dev/null
  bundle install
  bundle exec rspec spec
popd > /dev/null
