#!/usr/bin/env bash
set -uo pipefail

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
source $script_dir/helpers.sh

if [[ "$(whoami)" != "root" ]]; then
  echo "ordnance-survey needs to be run as root" 1>&2
  exit 1
fi

printSection "Sit Back, Relax and enjoy the fire"
printBanner

tmp_dir=$(mktemp -d -t tmp.XXXXXXXXXX)
os_report_dir="${tmp_dir}/os-report"
mkdir -p "$os_report_dir"

function cleanup {
  rm -rf "$tmp_dir"
}
trap cleanup EXIT

pushd "$os_report_dir" > /dev/null
  printAndCollect "Date" date date.log
  printAndCollect "Hostname" hostname hostname.log
  printAndCollect "Free Memory" "free -mt" free.log
  printAndCollect "Kernel Details" "uname -a" uname.log
  printAndCollect "Uptime" uptime uptime.log
  printAndCollect "Disk Usage" "df -h" df.log
  printAndCollect "Process Tree" "ps aux --forest" forest.log

  collect "Kernel Messages" "dmesg -T" dmesg.log
  collect "Network Interfaces" ifconfig ifconfig.log
  collect "IP Tables" "iptables -L" iptables-L.log
  collect "NAT IP Tables" "iptables -tnat -L" iptables-tnat.log
  collect "Mount Table" "cat /proc/self/mountinfo" mountinfo.log
  collect "Garden Version" "/var/vcap/packages/guardian/bin/gdn -v" gdn-version.log
  collect "Garden Depot Contents" "find /var/vcap/data/garden/depot | sed 's|[^/]*/|- |g'" depot-contents.log

  archive "Kernel Log" /var/log kern.log
  archive "Monit Log" /var/vcap/monit monit.log
  archive "Garden config.ini" /var/vcap/jobs/garden/config config.ini
  archiveDir "Garden Logs" /var/vcap/sys/log/garden garden_logs.tgz
popd > /dev/null

printSection "Creating OS Report Archive"
if tar zcf os-report.tgz -C "$tmp_dir" .; then
  printSection "OS Report Complete. Archive os-report.tgz created"
else
  printFailed
fi

