#!/usr/bin/env bash
set -uo pipefail

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
source $script_dir/helpers.sh

if grep -q garden_start /proc/1/cmdline; then
  printRed "Keep Calm and Re-run outside the BPM Container "
  exit 1
fi

if [[ "$(whoami)" != "root" ]]; then
  printRed "Keep Calm and Re-run as Root"
  exit 1
fi

export TMPDIR=/var/vcap/data/tmp

printBanner

tmp_dir=$(mktemp -d -t tmp.XXXXXXXXXX)
os_report_dir="${tmp_dir}/os-report"
mkdir -p "$os_report_dir"

function cleanup {
  rm -rf "$tmp_dir"
}
trap cleanup EXIT

pushd "$os_report_dir" > /dev/null
  printGreen "<Useful information below, please copy-paste from here>"

  printAndCollect "Date" "date" date.log
  printAndCollect "Uptime" "uptime" uptime.log
  printAndCollect "Garden Version" "/var/vcap/packages/guardian/bin/gdn -v" gdn-version.log
  printAndCollect "Hostname" "hostname" hostname.log
  printAndCollect "Memory Usage" "free -mt" free.log
  printAndCollect "Kernel Details" "uname -a" uname.log
  printAndCollect "Monit Summary" "/var/vcap/bosh/bin/monit summary" monit-summary.log
  printAndCollect "Number of Containers" "ls /var/vcap/data/garden/depot/ | wc -w" num-containers.log
  printAndCollect "Number of Open Files" "lsof 2> /dev/null | wc -l" num-open-files.log
  printAndCollect "Max Number of Open Files" "cat /proc/sys/fs/file-max" file-max.log

  collect "Disk Usage" "df -h" df.log
  collect "Process Information" "ps -eLo pid,tid,ppid,user:11,comm,state,wchan:20,lstart" ps-info.log
  collect "Process Tree" "ps aux --forest" ps-forest.log
  collect "Kernel Messages" "dmesg -T" dmesg.log
  collect "Network Interfaces" "ifconfig" ifconfig.log
  collect "IP Tables" "iptables -L" iptables-L.log
  collect "NAT IP Tables" "iptables -tnat -L" iptables-tnat.log
  collect "Mount Table" "cat /proc/$(pidof gdn)/mountinfo" mountinfo.log
  collect "Garden Depot Contents" "find /var/vcap/data/garden/depot | sed 's|[^/]*/|- |g'" depot-contents.log

  collectFiles "Kernel Log" /var/log/kern.log* kern-logs
  collectFiles "Syslog (may fail on BOSH Lite)" /var/log/syslog* syslogs
  collectFiles "Monit Log" /var/vcap/monit/monit.log* monit-logs
  collectFile "Garden config.ini" /var/vcap/jobs/garden/config/config.ini config.ini
  archiveDir "Garden Logs" /var/vcap/sys/log/garden garden_logs.tgz
popd > /dev/null

printSection "Creating OS Report Archive"

filename="$(hostname)_$(date '+%F-%H-%M-%S')"
if tar zcf "$TMPDIR/os-report-$filename.tgz" -C "$tmp_dir" .; then
  printGreen "Report Complete. Archive Created: ${TMPDIR}/os-report-$filename.tgz"
else
  printFailed
fi

