#!/bin/bash
# vim: set ft=sh

set -e -x
set -o pipefail

export GOPATH=$PWD
export PATH=$PWD/bin:$PATH

export ROOT_DIR=$PWD

cd src/code.cloudfoundry.org/garden-performance-acceptance-tests
ACK_GINKGO_DEPRECATIONS=1.16.4 ginkgo -mod vendor -nodes=1 "$@" | tee output.txt

tail -n 15 output.txt | grep Time | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g" >$ROOT_DIR/stats/stats.txt
