#!/usr/bin/env bash

set -euxo pipefail

release=$PWD/release

export BINARIES="${release}/bin"
export PATH=$HOME/go/bin:${BINARIES}:$PATH

# This is work around --buildvcs issues in Go 1.18+
git config --global --add safe.directory '*'

function build() {
  # shellcheck source=../helpers/build-binaries.bash
  source "$release/ci/helpers/build-binaries.bash"

  mkdir -p "${BINARIES}"
  build_runc "$release" "${BINARIES}"
  build_grootfs "$release" "${BINARIES}"

  if [[ "$CONTAINERD_ENABLED" == "true" ]] ; then
    build_containerd "$release" "${BINARIES}"
  fi
}

function prepare() {
  # shellcheck source=../helpers/device-control.bash
  source "$release/ci/helpers/device-control.bash"
  permit_device_control
  create_loop_devices 256
  # Set up AppArmor
  if ! grep securityfs /proc/self/mounts > /dev/null 2>&1 ; then
    mount -t securityfs securityfs /sys/kernel/security
  fi
  apparmor_parser -r /opt/static-assets/garden-default

}

function test() {
  #rootfses required in tests
  export GARDEN_TEST_ROOTFS=/opt/warden/rootfs.tar
  export GARDEN_FUSE_TEST_ROOTFS=/opt/warden/fuse-rootfs.tar
  export GARDEN_DOCKER_REGISTRY_V2_TEST_ROOTFS=/opt/warden/docker-registry-v2-rootfs.tar

  # binaries required for running tests
  export GARDEN_TAR_PATH="$PWD/tar-out/tar"
  export BINARIES="${BINARIES}"

  # Test combinations
  export CONTAINERD_ENABLED="${CONTAINERD_ENABLED}"
  export CONTAINERD_FOR_PROCESSES_ENABLED="${CONTAINERD_FOR_PROCESSES_ENABLED}"
  export CPU_THROTTLING_ENABLED="${CPU_THROTTLING_ENABLED}"

  go version

  cd "${release}/src/guardian"

  go vet ./...
  go run github.com/onsi/ginkgo/v2/ginkgo -tags daemon -r -p --keepx-going --nodes=${GINKGO_NODES} --fail-on-pending --randomize-suites --randomize-all -debug --race $*
}

build
prepare
test "$*"
